name: simple_mlops
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -v
      - name: deploy to render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_APP_ID: ${{ secrets.RENDER_APP_ID }}
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: |
          curl --request POST \
          --url https://api.render.com/v1/services/$RENDER_APP_ID/deploys \
          --header 'accept: application/json' \
          --header 'authorization: Bearer $RENDER_API_KEY' \
          --header 'content-type: application/json'
